uncertRuns <- function(case = 'all', years = 1){
  if (case == 'all'){
    initial_condition_uncertainty <- TRUE
    host_uncertainty <- TRUE
    parameter_cov_matrix <- read.table('parameters/eu1_2019_cov_mat.csv', header = F)
    eu1_all <- PoPS::pops_multirun(infected_file,
                                 host_file,
                                 total_populations_file,
                                 parameter_means,
                                 parameter_cov_matrix,
                                 temp,
                                 temperature_coefficient_file,
                                 precip,
                                 precipitation_coefficient_file,
                                 model_type,
                                 latency_period,
                                 time_step,
                                 season_month_start,
                                 season_month_end,
                                 start_date,
                                 end_date,
                                 use_survival_rates,
                                 survival_rate_month,
                                 survival_rate_day,
                                 survival_rates_file,
                                 use_lethal_temperature,
                                 temperature_file,
                                 lethal_temperature,
                                 lethal_temperature_month,
                                 mortality_on,
                                 mortality_rate,
                                 mortality_time_lag,
                                 mortality_frequency,
                                 mortality_frequency_n,
                                 management,
                                 treatment_dates,
                                 treatments_file,
                                 treatment_method,
                                 natural_kernel_type,
                                 anthropogenic_kernel_type,
                                 natural_dir,
                                 anthropogenic_dir,
                                 number_of_iterations,
                                 number_of_cores,
                                 pesticide_duration,
                                 pesticide_efficacy,
                                 random_seed,
                                 output_frequency,
                                 output_frequency_n,
                                 movements_file,
                                 use_movements,
                                 start_exposed,
                                 generate_stochasticity,
                                 establishment_stochasticity,
                                 movement_stochasticity,
                                 dispersal_stochasticity,
                                 establishment_probability,
                                 dispersal_percentage,
                                 quarantine_areas_file,
                                 use_quarantine,
                                 use_spreadrates,
                                 use_overpopulation_movements,
                                 overpopulation_percentage,
                                 leaving_percentage,
                                 leaving_scale_coefficient,
                                 exposed_file,
                                 mask,
                                 write_outputs,
                                 output_folder_path,
                                 network_filename,
                                 network_movement,
                                 initial_condition_uncertainty,
                                 host_uncertainty)
    terra::writeRaster(eu1_all$simulation_mean, 'All_Mean.tif')
    terra::writeRaster(eu1_all$simulation_sd, 'All_SD.tif')
    out = cbind(eu1_all$number_infecteds, eu1_all$infected_areas)
    colnames(out) <- rep(c('num all', 'area all'), years)
    return(out)
  }
  if (case == 'nohost'){
    initial_condition_uncertainty <- TRUE
    host_uncertainty <- FALSE
    parameter_cov_matrix <- read.table('parameters/eu1_2019_cov_mat.csv', header = F)
    eu1_nohost <- PoPS::pops_multirun(infected_file,
                             host_file,
                             total_populations_file,
                             parameter_means,
                             parameter_cov_matrix,
                             temp,
                             temperature_coefficient_file,
                             precip,
                             precipitation_coefficient_file,
                             model_type,
                             latency_period,
                             time_step,
                             season_month_start,
                             season_month_end,
                             start_date,
                             end_date,
                             use_survival_rates,
                             survival_rate_month,
                             survival_rate_day,
                             survival_rates_file,
                             use_lethal_temperature,
                             temperature_file,
                             lethal_temperature,
                             lethal_temperature_month,
                             mortality_on,
                             mortality_rate,
                             mortality_time_lag,
                             mortality_frequency,
                             mortality_frequency_n,
                             management,
                             treatment_dates,
                             treatments_file,
                             treatment_method,
                             natural_kernel_type,
                             anthropogenic_kernel_type,
                             natural_dir,
                             anthropogenic_dir,
                             number_of_iterations,
                             number_of_cores,
                             pesticide_duration,
                             pesticide_efficacy,
                             random_seed,
                             output_frequency,
                             output_frequency_n,
                             movements_file,
                             use_movements,
                             start_exposed,
                             generate_stochasticity,
                             establishment_stochasticity,
                             movement_stochasticity,
                             dispersal_stochasticity,
                             establishment_probability,
                             dispersal_percentage,
                             quarantine_areas_file,
                             use_quarantine,
                             use_spreadrates,
                             use_overpopulation_movements,
                             overpopulation_percentage,
                             leaving_percentage,
                             leaving_scale_coefficient,
                             exposed_file,
                             mask,
                             write_outputs,
                             output_folder_path,
                             network_filename,
                             network_movement,
                             initial_condition_uncertainty,
                             host_uncertainty)
    terra::writeRaster(eu1_nohost$simulation_mean, 'NoHost_Mean.tif')
    terra::writeRaster(eu1_nohost$simulation_sd, 'NoHost_SD.tif')
    out = cbind(eu1_nohost$number_infecteds, eu1_nohost$infected_areas)
    colnames(out) <- rep(c('num nohost', 'area nohost'), years)
    return(out)
  }
  if (case == 'noic'){
    initial_condition_uncertainty <- FALSE
    host_uncertainty <- TRUE
    parameter_cov_matrix <- read.table('parameters/eu1_2019_cov_mat.csv', header = F)
    eu1_noic <- PoPS::pops_multirun(infected_file,
                             host_file,
                             total_populations_file,
                             parameter_means,
                             parameter_cov_matrix,
                             temp,
                             temperature_coefficient_file,
                             precip,
                             precipitation_coefficient_file,
                             model_type,
                             latency_period,
                             time_step,
                             season_month_start,
                             season_month_end,
                             start_date,
                             end_date,
                             use_survival_rates,
                             survival_rate_month,
                             survival_rate_day,
                             survival_rates_file,
                             use_lethal_temperature,
                             temperature_file,
                             lethal_temperature,
                             lethal_temperature_month,
                             mortality_on,
                             mortality_rate,
                             mortality_time_lag,
                             mortality_frequency,
                             mortality_frequency_n,
                             management,
                             treatment_dates,
                             treatments_file,
                             treatment_method,
                             natural_kernel_type,
                             anthropogenic_kernel_type,
                             natural_dir,
                             anthropogenic_dir,
                             number_of_iterations,
                             number_of_cores,
                             pesticide_duration,
                             pesticide_efficacy,
                             random_seed,
                             output_frequency,
                             output_frequency_n,
                             movements_file,
                             use_movements,
                             start_exposed,
                             generate_stochasticity,
                             establishment_stochasticity,
                             movement_stochasticity,
                             dispersal_stochasticity,
                             establishment_probability,
                             dispersal_percentage,
                             quarantine_areas_file,
                             use_quarantine,
                             use_spreadrates,
                             use_overpopulation_movements,
                             overpopulation_percentage,
                             leaving_percentage,
                             leaving_scale_coefficient,
                             exposed_file,
                             mask,
                             write_outputs,
                             output_folder_path,
                             network_filename,
                             network_movement,
                             initial_condition_uncertainty,
                             host_uncertainty)
    terra::writeRaster(eu1_noic$simulation_mean, 'NoIC_Mean.tif')
    terra::writeRaster(eu1_noic$simulation_sd, 'NoIC_SD.tif')
    out = cbind(eu1_noic$number_infecteds, eu1_noic$infected_areas)
    colnames(out) <- rep(c('num noic', 'area noic'), years)
    return(out)
  }
  if (case == 'nopar'){
    initial_condition_uncertainty <- TRUE
    host_uncertainty <- TRUE
    parameter_cov_matrix <- matrix(0,8,8)
    eu1_nopar <- PoPS::pops_multirun(infected_file,
                                  host_file,
                                  total_populations_file,
                                  parameter_means,
                                  parameter_cov_matrix,
                                  temp,
                                  temperature_coefficient_file,
                                  precip,
                                  precipitation_coefficient_file,
                                  model_type,
                                  latency_period,
                                  time_step,
                                  season_month_start,
                                  season_month_end,
                                  start_date,
                                  end_date,
                                  use_survival_rates,
                                  survival_rate_month,
                                  survival_rate_day,
                                  survival_rates_file,
                                  use_lethal_temperature,
                                  temperature_file,
                                  lethal_temperature,
                                  lethal_temperature_month,
                                  mortality_on,
                                  mortality_rate,
                                  mortality_time_lag,
                                  mortality_frequency,
                                  mortality_frequency_n,
                                  management,
                                  treatment_dates,
                                  treatments_file,
                                  treatment_method,
                                  natural_kernel_type,
                                  anthropogenic_kernel_type,
                                  natural_dir,
                                  anthropogenic_dir,
                                  number_of_iterations,
                                  number_of_cores,
                                  pesticide_duration,
                                  pesticide_efficacy,
                                  random_seed,
                                  output_frequency,
                                  output_frequency_n,
                                  movements_file,
                                  use_movements,
                                  start_exposed,
                                  generate_stochasticity,
                                  establishment_stochasticity,
                                  movement_stochasticity,
                                  dispersal_stochasticity,
                                  establishment_probability,
                                  dispersal_percentage,
                                  quarantine_areas_file,
                                  use_quarantine,
                                  use_spreadrates,
                                  use_overpopulation_movements,
                                  overpopulation_percentage,
                                  leaving_percentage,
                                  leaving_scale_coefficient,
                                  exposed_file,
                                  mask,
                                  write_outputs,
                                  output_folder_path,
                                  network_filename,
                                  network_movement,
                                  initial_condition_uncertainty,
                                  host_uncertainty)
    terra::writeRaster(eu1_nopar$simulation_mean, 'NoPar_Mean.tif')
    terra::writeRaster(eu1_nopar$simulation_sd, 'NoPar_SD.tif')
    out = cbind(eu1_nopar$number_infecteds, eu1_nopar$infected_areas)
    colnames(out) <- rep(c('num nopar', 'area nopar'), years)
    return(out)
  }
  if (case == 'host'){
    initial_condition_uncertainty <- FALSE
    host_uncertainty <- TRUE
    parameter_cov_matrix <- matrix(0,8,8)
    eu1_host <- PoPS::pops_multirun(infected_file,
                                      host_file,
                                      total_populations_file,
                                      parameter_means,
                                      parameter_cov_matrix,
                                      temp,
                                      temperature_coefficient_file,
                                      precip,
                                      precipitation_coefficient_file,
                                      model_type,
                                      latency_period,
                                      time_step,
                                      season_month_start,
                                      season_month_end,
                                      start_date,
                                      end_date,
                                      use_survival_rates,
                                      survival_rate_month,
                                      survival_rate_day,
                                      survival_rates_file,
                                      use_lethal_temperature,
                                      temperature_file,
                                      lethal_temperature,
                                      lethal_temperature_month,
                                      mortality_on,
                                      mortality_rate,
                                      mortality_time_lag,
                                      mortality_frequency,
                                      mortality_frequency_n,
                                      management,
                                      treatment_dates,
                                      treatments_file,
                                      treatment_method,
                                      natural_kernel_type,
                                      anthropogenic_kernel_type,
                                      natural_dir,
                                      anthropogenic_dir,
                                      number_of_iterations,
                                      number_of_cores,
                                      pesticide_duration,
                                      pesticide_efficacy,
                                      random_seed,
                                      output_frequency,
                                      output_frequency_n,
                                      movements_file,
                                      use_movements,
                                      start_exposed,
                                      generate_stochasticity,
                                      establishment_stochasticity,
                                      movement_stochasticity,
                                      dispersal_stochasticity,
                                      establishment_probability,
                                      dispersal_percentage,
                                      quarantine_areas_file,
                                      use_quarantine,
                                      use_spreadrates,
                                      use_overpopulation_movements,
                                      overpopulation_percentage,
                                      leaving_percentage,
                                      leaving_scale_coefficient,
                                      exposed_file,
                                      mask,
                                      write_outputs,
                                      output_folder_path,
                                      network_filename,
                                      network_movement,
                                      initial_condition_uncertainty,
                                      host_uncertainty)
    terra::writeRaster(eu1_host$simulation_mean, 'Host_Mean.tif')
    terra::writeRaster(eu1_host$simulation_sd, 'Host_SD.tif')
    out = cbind(eu1_host$number_infecteds, eu1_host$infected_areas)
    colnames(out) <- rep(c('num host', 'area host'), years)
    return(out)
  }
  if (case == 'ic'){
    initial_condition_uncertainty <- TRUE
    host_uncertainty <- FALSE
    parameter_cov_matrix <- matrix(0,8,8)
    eu1_ic <- PoPS::pops_multirun(infected_file,
                                    host_file,
                                    total_populations_file,
                                    parameter_means,
                                    parameter_cov_matrix,
                                    temp,
                                    temperature_coefficient_file,
                                    precip,
                                    precipitation_coefficient_file,
                                    model_type,
                                    latency_period,
                                    time_step,
                                    season_month_start,
                                    season_month_end,
                                    start_date,
                                    end_date,
                                    use_survival_rates,
                                    survival_rate_month,
                                    survival_rate_day,
                                    survival_rates_file,
                                    use_lethal_temperature,
                                    temperature_file,
                                    lethal_temperature,
                                    lethal_temperature_month,
                                    mortality_on,
                                    mortality_rate,
                                    mortality_time_lag,
                                    mortality_frequency,
                                    mortality_frequency_n,
                                    management,
                                    treatment_dates,
                                    treatments_file,
                                    treatment_method,
                                    natural_kernel_type,
                                    anthropogenic_kernel_type,
                                    natural_dir,
                                    anthropogenic_dir,
                                    number_of_iterations,
                                    number_of_cores,
                                    pesticide_duration,
                                    pesticide_efficacy,
                                    random_seed,
                                    output_frequency,
                                    output_frequency_n,
                                    movements_file,
                                    use_movements,
                                    start_exposed,
                                    generate_stochasticity,
                                    establishment_stochasticity,
                                    movement_stochasticity,
                                    dispersal_stochasticity,
                                    establishment_probability,
                                    dispersal_percentage,
                                    quarantine_areas_file,
                                    use_quarantine,
                                    use_spreadrates,
                                    use_overpopulation_movements,
                                    overpopulation_percentage,
                                    leaving_percentage,
                                    leaving_scale_coefficient,
                                    exposed_file,
                                    mask,
                                    write_outputs,
                                    output_folder_path,
                                    network_filename,
                                    network_movement,
                                    initial_condition_uncertainty,
                                    host_uncertainty)
    terra::writeRaster(eu1_ic$simulation_mean, 'IC_Mean.tif')
    terra::writeRaster(eu1_ic$simulation_sd, 'IC_SD.tif')
    out = cbind(eu1_ic$number_infecteds, eu1_ic$infected_areas)
    colnames(out) <- rep(c('num ic', 'area ic'), years)
    return(out)
  }
  if (case == 'par'){
    initial_condition_uncertainty <- FALSE
    host_uncertainty <- FALSE
    parameter_cov_matrix <- read.table('parameters/eu1_2019_cov_mat.csv', header = F)
    eu1_par <- PoPS::pops_multirun(infected_file,
                                     host_file,
                                     total_populations_file,
                                     parameter_means,
                                     parameter_cov_matrix,
                                     temp,
                                     temperature_coefficient_file,
                                     precip,
                                     precipitation_coefficient_file,
                                     model_type,
                                     latency_period,
                                     time_step,
                                     season_month_start,
                                     season_month_end,
                                     start_date,
                                     end_date,
                                     use_survival_rates,
                                     survival_rate_month,
                                     survival_rate_day,
                                     survival_rates_file,
                                     use_lethal_temperature,
                                     temperature_file,
                                     lethal_temperature,
                                     lethal_temperature_month,
                                     mortality_on,
                                     mortality_rate,
                                     mortality_time_lag,
                                     mortality_frequency,
                                     mortality_frequency_n,
                                     management,
                                     treatment_dates,
                                     treatments_file,
                                     treatment_method,
                                     natural_kernel_type,
                                     anthropogenic_kernel_type,
                                     natural_dir,
                                     anthropogenic_dir,
                                     number_of_iterations,
                                     number_of_cores,
                                     pesticide_duration,
                                     pesticide_efficacy,
                                     random_seed,
                                     output_frequency,
                                     output_frequency_n,
                                     movements_file,
                                     use_movements,
                                     start_exposed,
                                     generate_stochasticity,
                                     establishment_stochasticity,
                                     movement_stochasticity,
                                     dispersal_stochasticity,
                                     establishment_probability,
                                     dispersal_percentage,
                                     quarantine_areas_file,
                                     use_quarantine,
                                     use_spreadrates,
                                     use_overpopulation_movements,
                                     overpopulation_percentage,
                                     leaving_percentage,
                                     leaving_scale_coefficient,
                                     exposed_file,
                                     mask,
                                     write_outputs,
                                     output_folder_path,
                                     network_filename,
                                     network_movement,
                                     initial_condition_uncertainty,
                                     host_uncertainty)
    terra::writeRaster(eu1_par$simulation_mean, 'Par_Mean.tif')
    terra::writeRaster(eu1_par$simulation_sd, 'Par_SD.tif')
    out = cbind(eu1_par$number_infecteds, eu1_par$infected_areas)
    colnames(out) <- rep(c('num par', 'area par'), years)
    return(out)
  }
  if (case == 'none'){
    initial_condition_uncertainty <- FALSE
    host_uncertainty <- FALSE
    parameter_cov_matrix <- matrix(0,8,8)
    eu1_none <- PoPS::pops_multirun(infected_file,
                             host_file,
                             total_populations_file,
                             parameter_means,
                             parameter_cov_matrix,
                             temp,
                             temperature_coefficient_file,
                             precip,
                             precipitation_coefficient_file,
                             model_type,
                             latency_period,
                             time_step,
                             season_month_start,
                             season_month_end,
                             start_date,
                             end_date,
                             use_survival_rates,
                             survival_rate_month,
                             survival_rate_day,
                             survival_rates_file,
                             use_lethal_temperature,
                             temperature_file,
                             lethal_temperature,
                             lethal_temperature_month,
                             mortality_on,
                             mortality_rate,
                             mortality_time_lag,
                             mortality_frequency,
                             mortality_frequency_n,
                             management,
                             treatment_dates,
                             treatments_file,
                             treatment_method,
                             natural_kernel_type,
                             anthropogenic_kernel_type,
                             natural_dir,
                             anthropogenic_dir,
                             number_of_iterations,
                             number_of_cores,
                             pesticide_duration,
                             pesticide_efficacy,
                             random_seed,
                             output_frequency,
                             output_frequency_n,
                             movements_file,
                             use_movements,
                             start_exposed,
                             generate_stochasticity,
                             establishment_stochasticity,
                             movement_stochasticity,
                             dispersal_stochasticity,
                             establishment_probability,
                             dispersal_percentage,
                             quarantine_areas_file,
                             use_quarantine,
                             use_spreadrates,
                             use_overpopulation_movements,
                             overpopulation_percentage,
                             leaving_percentage,
                             leaving_scale_coefficient,
                             exposed_file,
                             mask,
                             write_outputs,
                             output_folder_path,
                             network_filename,
                             network_movement,
                             initial_condition_uncertainty,
                             host_uncertainty)
    terra::writeRaster(eu1_none$simulation_mean, 'None_Mean.tif')
    terra::writeRaster(eu1_none$simulation_sd, 'None_SD.tif')
    out = cbind(eu1_none$number_infecteds, eu1_none$infected_areas)
    colnames(out) <- rep(c('num none', 'area none'), years)
    return(out)
  }
}

